repos:
  - repo: local
    hooks:
      - id: mdformat-obsidian
        name: mdformat with Obsidian and GFM support
        entry: python Scripts/mdformat_obsidian.py  # This runs your custom plugin script
        language: python
        files: \.md$
        additional_dependencies: ['mdformat', 'mdformat-gfm']  # Adding GFM plugin

  # Markdownlint hook remains the same
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args: [--fix]

